<!doctype html>  

<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <?php echo $this->headTitle(); ?>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">


    <?php echo $this->headLink()
		->appendStylesheet($this->themePath('css/style.css?v=2'))
		->appendStylesheet("/common/jquery-ui-1.8.9.custom/css/prizym/jquery-ui-1.8.9.custom.css")
		->headLink(array(
		    'type' => 'text/css',
		    'rel'  => 'stylesheet/less',
		    'href' => $this->themePath('css/admin.less')
		)); ?>
    
    <script src="/common/js/less.1.0.41.js" type="text/javascript"></script>
    <script type="text/javascript">
        less.env = 'development';
        less.watch();
    </script>

</head>

<body>

    <div id="container">
        <aside id="sidebar">
             <header>
                 <h2>Prizym</h2>
                 <h3>Your Site</h3>
                 <p>
                     <a href="#">Andrew Cobby <img src="/common/icons/user_green.png" alt="User"></a>
                     <a href="#">Logout <img src="/common/icons/lock_open.png" alt="Logout"></a>
                 </p>
             </header>
             
             <section>
                 <h3><a href="#">Dashboard <img src="/common/icons/bricks.png"></a></h3>
             </section>
             
             <section>
                 <h3>Posts <img src="/common/icons/page_add.png" alt="New Post"></h3>
                 <ul>
                     <li><a href="#">New Post</a></li>
                     <li><a href="#">View Posts</a></li>
                 </ul>
             </section>
             
             <section class="current">
                 <h3>Section</span></h3>
                 <ul>
                     <li class="current"><a href="#">Some Action</a></li>
                     <li><a href="#">Some Action</a></li>
                     <li><a href="#">Some Action</a></li>
                 </ul>
             </section>
             
             <section>
                 <h3>Section</h3>
                 <ul>
                     <li><a href="#">Some Action</a></li>
                     <li><a href="#">Some Action</a></li>
                     <li><a href="#">Some Action</a></li>
                 </ul>
             </section>
        </aside> 
        
        <div id="main">
            <?php echo $this->layout()->content; ?>
        </div>  
    </div> <!-- end of #container -->


    <?php echo $this->headScript()
		->prependFile($this->themePath('js/libs/modernizr-1.6.min.js'))
		->prependFile("/common/jquery-ui-1.8.9.custom/js/jquery-ui-1.8.9.custom.min.js")
		->prependFile("/common/jquery-ui-1.8.9.custom/js/jquery-1.4.4.min.js"); ?>


    <!--[if lt IE 7 ]>
    <script src="js/libs/dd_belatedpng.js"></script>
    <script> DD_belatedPNG.fix('img, .png_bg'); </script>
    <![endif]-->

    <!-- yui profiler and profileviewer - remove for production 
    <script src="js/profiling/yahoo-profiling.min.js"></script>
    <script src="js/profiling/config.js"></script>
    end profiling code -->


    <!-- change the UA-XXXXX-X to be your site's ID -->
    <script>
    /*var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
    (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
    })(document, 'script');*/
    </script>
  
</body>
</html>