<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    
    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    
    <title>A HTML5 and CSS3 theme by Jayj.dk</title>
    
    <meta name="description" content="" />
    
    <link href="css/960.css" rel="stylesheet" type="text/css" />
    <link href="style.css" rel="stylesheet" type="text/css" />
    
    <!--[if lt IE 9]>
    	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    
    <!--[if lte IE 7]>
    	<link href="css/ie.css" rel="stylesheet" type="text/css" />
    <![endif]-->

</head>

<body>

<div id="wrapper" class="container_12">

    <header id="header" class="grid_12">
    
    	<h1><a href="index.html">A CSS3 Theme</a></h1>
    
    </header> <!-- end header -->
    
    <div id="content">
    
        <nav>
            <ul id="menu" class="clearfix"> 
                <li class="current"><a href="index.html">Home</a></li>
                <li>
                	<a href="about.html">About</a>
                    <ul>
                        <li><a href="about.html">Subpage</a></li>
                        <li><a href="about.html">Subpage 2</a></li>
                    </ul>
                </li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
            <br class="clear" />
        </nav>
    
        <!-- Show a "Please Upgrade" box to both IE7 and IE6 users (Edit to IE 6 if you just want to show it to IE6 users) - jQuery will load the content from js/ie.html into the div -->
        
        <!--[if lte IE 7]>
        	<div class="ie grid_7"></div>
        <![endif]-->
    
    <div id="main" class="grid_8 alpha">
	<?= $this->layout()->content; ?>
        <!-- <article class="post">
        
            <h2><a href="#">Post heading</a></h2>
            
            <a href="#"><img src="images/thumbnail.jpg" alt="" class="thumbnail alignleft" /></a>
            
            <p>
                Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. 
                Separated they live in <a href="#">Bookmarksgrove right at the coast of the Semantics</a>, a large language ocean. 
                A small river named Duden flows by their place and supplies it with the necessary regelialia. 
                It is a paradisematic country, in which roasted parts of sentences fly into your mouth. 
            </p>
            
            <p>
                Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life.
                One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. 
            </p>
            
            <div class="clear"></div>  
            
            <footer class="postmeta">
                <span class="btn alignleft">
                	In <a href="#">Category</a> by <a href="#">Jay</a> on <time datetime="2010-09-05" pubdate>September 5th, 2010</time>
				</span>
                <a href="#" class="more-link alignright">Read more</a>
            </footer> <!-- end post meta
        
        </article> <!-- end post 1 -->
        
    
    </div> <!-- end main -->
    
    <div id="sidebar" class="grid_4 omega">
    
        <aside class="widget">
            <h3>Sidebar heading</h3>
            
            <ul>
                <li><a href="#">Li element</a></li>
                <li><a href="#">Li element</a></li>
                <li><a href="#">Li element</a></li>
                <li><a href="#">Li element</a></li>
                <li><a href="#">Li element</a></li>
            </ul>
        </aside> <!-- end widget -->
        
        <aside class="widget">
            <!-- Non working search -->
            <form action="">
                <input type="search" results="10" placeholder="Search..." />
                <input type="submit" value="Search..." />
            </form>
        </aside> <!-- end widget -->
        
        <aside class="widget">
            <h3>Widget</h3>
            
            <p>
                Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life.
                One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. 
            </p>
        </aside> <!-- end widget -->
    
    </div> <!-- end sidebar -->
    
    </div> <!-- end content -->
    
    <footer id="footer" class="grid_12">
        <!-- You're free to remove the credit link in the footer, but please, please leave it there. -->
        <p>Copyright &copy; 2010 <a href="#">Sitename.com</a> - Design by <a href="http://jayj.dk" title="Design by Jayj.dk">Jayj.dk</a></p>
    </footer> <!-- end footer -->
    
    <div class="clear"></div>

</div> <!-- end wrapper -->

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script type="text/javascript" src="js/script.js"></script>

</body>
</html>